version: "3"
services:
  server:
    build: ./server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
      DATABASE_URL: postgresql://root@db:26257/${DB_NAME}?sslmode=disable
      NODE_ENV: test
      HOSTNAME: localhost
      ADMIN_EMAIL: test@test.com
      APP_KEY: supersecretsauce
      API_TOKEN: supersecretspicysauce
      SPACES_ACCESS_KEY_ID: spaces_access_key
      SPACES_SECRET_ACCESS_KEY: spaces_secret_key
      SPACES_REGION: spaces_region
      SPACES_BUCKET: spaces_bucket
      SPACES_ENDPOINT: spaces_endpoint
    healthcheck:
      test: ["CMD", "curl", "http://server:3333"]
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 30s
    command: yarn run dev
  db:
    image: cockroachdb/cockroach:latest
    ports:
      # Port for connecting to the DB
      - "26257:26257"
      # Port for dashboard
      - "8080:8080"
    environment:
      COCKROACH_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD", "curl", "http://db:8080/health?ready=1"]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 10s
    command: start-single-node --insecure
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      API_TOKEN: supersecretspicysauce
      NODE_ENV: test
    healthcheck:
      test: ["CMD", "curl", "http://client:3000"]
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 30s
    command: yarn run start
  browser_test:
    build: ./browser_test
    depends_on:
      client:
        condition: service_healthy
      server:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./browser_test/cypress/screenshots:/app/cypress/screenshots
    # Need to use 'host' network mode to avoid cross-host errors
    # from Webpack server
    network_mode: "host"
