version: "3.2"
services:
  server:
    build: ./server
    volumes:
      - ./server:/app
      - productcatalog_server_node_modules:/app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      PORT: 3333
      DATABASE_URL: postgresql://root@db:26257/${DB_NAME}?sslmode=disable
      NODE_ENV: ${NODE_ENV:-development}
      HOSTNAME: localhost
      ADMIN_EMAIL: test@test.com
      APP_KEY: supersecretsauce
      API_TOKEN: supersecretspicysauce
      SPACES_ACCESS_KEY_ID: ${SPACES_ACCESS_KEY_ID:-""}
      SPACES_SECRET_ACCESS_KEY: ${SPACES_SECRET_ACCESS_KEY:-""}
      SPACES_REGION: ${SPACES_REGION:-""}
      SPACES_BUCKET: ${SPACES_BUCKET:-""}
      SPACES_ENDPOINT: ${SPACES_ENDPOINT:-""}
    env_file: .env
    stdin_open: true
    tty: true
    command: yarn run dev
  db:
    image: cockroachdb/cockroach:latest
    volumes:
      - ./database:/cockroach/database
    ports:
      # Port for connecting to the DB
      - "26257:26257"
      # Port for dashboard
      - "8080:8080"
    environment:
      COCKROACH_DATABASE: ${DB_NAME}
    command: start-single-node --insecure
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - productcatalog_client_node_modules:/app/node_modules
    depends_on:
      - server
    environment:
      API_TOKEN: supersecretspicysauce
      NODE_ENV: ${NODE_ENV:-development}
    command: yarn run start
  browser_test:
    build: ./browser_test
    depends_on:
      - client
      - server
    volumes:
      - ./browser_test:/app
      - /app/node_modules
    # Need to use 'host' network mode to avoid cross-host errors
    # from Webpack server
    network_mode: "host"
volumes:
  productcatalog_server_node_modules:
    external: true
  productcatalog_client_node_modules:
    external: true
