name: build

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        service: [server, client]
    env:
      SERVICE_NAME: ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: ./${{ env.SERVICE_NAME }}
          load: true
          tags: ${{ env.SERVICE_NAME }}
      - name: Check types
        run: docker run --rm $SERVICE_NAME:latest yarn run typecheck
      - name: Lint Typescript files
        run: docker run --rm $SERVICE_NAME:latest yarn run lint

  test:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: docker-compose -f docker-compose.ci.yml build
      - name: Run server unit tests
        run: docker-compose -f docker-compose.ci.yml run server yarn run test:unit
      - name: Run client unit tests
        run: docker-compose -f docker-compose.ci.yml run client yarn run test --watchAll=false
      - name: Run server integration tests
        run: ./scripts/integration_tests.sh docker-compose.ci.yml
      - name: Reset containers between test scripts
        run: docker-compose -f docker-compose.ci.yml down
      - name: Run browser end to end tests for client app
        id: e2e
        run: ./scripts/browser_tests.sh
      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.e2e.outcome == 'failure' }}
        with:
          name: e2e-screenshots
          path: browser_test/cypress/screenshots/

  next:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://root@localhost:26257/test?sslmode=disable
    steps:
      - uses: actions/checkout@v4
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          services: db
          compose-file: "docker-compose.ci.yml"
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Linting
        if: ${{ always() }}
        run: npm run lint
      - name: Check types
        if: ${{ always() }}
        run: npm run typecheck
      - name: Unit tests
        run: npm run test
      - name: Run e2e tests
        id: e2e
        run: npm run test:ci
      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.e2e.outcome == 'failure' }}
        with:
          name: e2e-screenshots
          path: cypress/screenshots/
