name: Test all the things

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        service: [server, client]
    env:
      SERVICE_NAME: ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: ./${{ env.SERVICE_NAME }}
          load: true
          tags: ${{ env.SERVICE_NAME }}
      - name: Lint Typescript files
        run: docker run --rm $SERVICE_NAME:latest yarn run lint

  test:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: docker-compose -f docker-compose.ci.yml build
      - name: Run server unit tests
        run: docker-compose -f docker-compose.ci.yml run server yarn run test:unit
      - name: Run client unit tests
        run: docker-compose -f docker-compose.ci.yml run client yarn run test --watchAll=false
      - name: Run server integration tests
        run: ./scripts/integration_tests.sh docker-compose.ci.yml
      - name: Reset containers between test scripts
        run: docker-compose -f docker-compose.ci.yml down
      - name: Run browser end to end tests for client app
        run: ./scripts/browser_tests.sh docker-compose.ci.yml browser_test localhost:3000
      - name: Run browser end to end tests for admin app
        run: ./scripts/browser_tests.sh docker-compose.ci.yml browser_test_admin localhost:3333
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: cypress-screenshots
          path: ./browser_test/cypress/screenshots/
